# Generated by Django 6.0 on 2025-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute_option_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='value_float',
        ),
        migrations.AddField(
            model_name='value',
            name='value_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text (String)'), ('integer', 'Integer (Number)'), ('decimal', 'decimal (Decimal Number)'), ('boolean', 'Boolean'), ('choice', 'Choice (Select from Options)')], default='text', max_length=10, verbose_name='Data Type'),
        ),
    ]
