# Generated by Django 6.0 on 2025-12-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='reference_id',
        ),
    ]
