# Generated by Django 6.0 on 2025-12-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_transaction_id_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(help_text='ID from abcd Stripe/PayPal', max_length=100, unique=True),
        ),
    ]
