# Generated by Django 6.0 on 2025-12-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(help_text='ID of transaction object (Checkout, Session, Order or whatever name it has) in Stripe/PayPal', max_length=100, unique=True),
        ),
    ]
